models:
  - ResNet50V2
  - InceptionResNetV2
  - MobileNetV2
  - MobileNet
  - EfficientNetB1
  - EfficientNetV2B1
  - EfficientNetV2S
  - ResNetRS101
  - ResNetRS152

dloss_scale: 0.5
memory_limit: 0
params_limit: 0
step_ratio: 0.2 # ste
astep_ratio: 0.1 # ste
num_partitions: 100
num_imported_submodels: 200
num_approx: 200
num_submodels_per_bunch: 100
num_samples_for_profiling: 5
pruning_exit: false

task:
  model_name: "efficientdet-d0"
  base_ckpt_path: "pretrained_weights/efficientdet-d0"
  model_dir: "temp"
  mixed_precision: false
  map_freq: 1
  strategy: ""
  use_fake_data: false
  use_xla: false
  batch_size: 4
  eval_samples: 548
  mode: "traineval"
  num_examples_per_epoch: 6471
  num_epochs: 100
  num_shards: 4
  train_file_pattern: "dataset/visdrone/tfrecord/train*.tfrecord"
  val_file_pattern: "dataset/visdrone/tfrecord/val*.tfrecord"
  image_size: 1024
  val_json_file: "dataset/visdrone/Convert-Visdrone-to-COCO/annotations_VisDrone_val.json"
  max_level: 7
  min_level: 3
  num_scales: 3
  #aspect_ratios:
  #  - 1.0
  #  - 2.0
  #  - 0.5
  anchor_scale: 4.0
  num_classes: 11
  heads:
    - "object_detection"
  regenerate_source_id: False
  groundtruth_is_crowd: null
  input_rand_hflip: True
  jitter_min: 0.1
  jitter_max: 2.0
  scale_range: False
  max_instances_per_image: 1000
  grid_mask: False
  autoaugment_policy: null
  target_size: null
  dataset_type: null
  drop_remainder: True
  debug: false

  optimizer: "adam"
  learning_rate: 0.008
  lr_warmup_init: 0.0008
  momentum: 0.9
  moving_average_decay: 0.9998
  weight_decay: 4.0e-5
  loss_scale: null
  use_hvd: False

  delta: 0.1
  iou_loss_type: null
  alpha: 0.25
  gamma: 1.5
  use_distillation: True
  label_smoothing: 0.1
  verbose: 1
  save_freq: "epoch"
